import fs from 'node:fs';
import path from 'node:path';
import { ensureDir } from '../paths.js';

/**
 * Readable markdown copies of HQ's state under .storyfront/log/, so the
 * history can be read (and diffed, and versioned) without HQ running.
 * Every ticket, decision and question gets an anchor, so IDs stay clickable.
 */
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ');
const day = (ts) => (ts ? ts.replace('T', ' ').slice(0, 16) : '');

export function channelFile(channel) {
  return `${channel.replace(/:/g, '-')}.md`;
}

export function renderBoard(state) {
  const tickets = Object.values(state.tickets).sort((a, b) => Number(a.id.split('-')[1]) - Number(b.id.split('-')[1]));
  const out = ['# Board', '', `Generated by Storyfront HQ. ${tickets.length} tickets.`, '', '| Ticket | Title | Status | Assignee | Epic | Depends on |', '|---|---|---|---|---|---|'];
  for (const t of tickets) {
    out.push(`| [${t.id}](#${t.id.toLowerCase()}) | ${esc(t.title)} | ${t.status} | ${t.assignee ?? ''} | ${t.epic ?? ''} | ${t.deps.map((d) => `[${d}](#${d.toLowerCase()})`).join(', ')} |`);
  }
  for (const t of tickets) {
    out.push('', `## <a id="${t.id.toLowerCase()}"></a>${t.id}: ${t.title}`, '');
    out.push(`- **Status:** ${t.status}${t.blockedBy.length ? ` (blocked by ${t.blockedBy.join(', ')})` : ''}`);
    out.push(`- **Assignee:** ${t.assignee ?? 'nobody'} · **Kind:** ${t.kind}${t.ui ? ' · UI' : ''} · **Attempts:** ${t.attempts}`);
    if (t.refs.length) out.push(`- **Refs:** ${t.refs.join(', ')}`);
    if (t.body) out.push('', t.body.trim());
    if (t.checkpoint) out.push('', `**Checkpoint** (${t.checkpoint.by}, ${day(t.checkpoint.ts)}): done — ${t.checkpoint.done}; next — ${t.checkpoint.next}`);
    if (t.activity.length) {
      out.push('', '| When | Who | What |', '|---|---|---|');
      for (const a of t.activity) out.push(`| ${day(a.ts)} | ${a.by} | ${esc(a.text)} |`);
    }
  }
  return out.join('\n') + '\n';
}

export function renderDecisions(state) {
  const out = ['# Decisions', '', 'Decisions the team made without you. Newest last.'];
  for (const d of state.decisions) {
    out.push('', `## <a id="${d.id.toLowerCase()}"></a>${d.id}: ${d.title}`, '', `- **By:** ${d.by}, ${day(d.ts)}${d.ticket ? ` · **Ticket:** ${d.ticket}` : ''}`, `- **Decision:** ${d.decision}`, `- **Why:** ${d.why}`);
    if (d.alternatives) out.push(`- **Alternatives:** ${d.alternatives}`);
    if (d.links?.length) out.push(`- **Links:** ${d.links.join(', ')}`);
  }
  return out.join('\n') + '\n';
}

export function renderQuestions(state) {
  const out = ['# Questions', '', 'Every question asked on the team, who it went to and the answer.'];
  for (const q of Object.values(state.questions)) {
    out.push('', `## <a id="${q.id.toLowerCase()}"></a>${q.id}: ${esc(q.question)}`, '', `- **From:** ${q.from} → **to:** ${q.to} (route: ${q.trail.join(' → ')})`, `- **Status:** ${q.status}${q.ticket ? ` · **Ticket:** ${q.ticket}` : ''}`);
    if (q.options.length) out.push(`- **Options:** ${q.options.join(' / ')}${q.recommended ? ` (recommended: ${q.recommended})` : ''}`);
    if (q.answer) out.push(`- **Answer** (${q.answeredBy}, ${day(q.answeredAt)}): ${q.answer}`);
  }
  return out.join('\n') + '\n';
}

export function renderChannel(channel, messages) {
  const out = [`# #${channel}`, ''];
  for (const m of messages) out.push(`**${m.by}** · ${day(m.ts)}  `, m.text, '');
  return out.join('\n');
}

export function createViewWriter(core, { delayMs = 400, onWritten } = {}) {
  const { store, paths } = core;
  let timer = null;
  const dirtyChannels = new Set();

  function writeAll() {
    timer = null;
    ensureDir(paths.chat);
    const s = store.state;
    fs.writeFileSync(path.join(paths.log, 'board.md'), renderBoard(s));
    fs.writeFileSync(path.join(paths.log, 'decisions.md'), renderDecisions(s));
    fs.writeFileSync(path.join(paths.log, 'questions.md'), renderQuestions(s));
    for (const c of dirtyChannels) {
      fs.writeFileSync(path.join(paths.chat, channelFile(c)), renderChannel(c, s.messages.filter((m) => m.channel === c)));
    }
    dirtyChannels.clear();
    onWritten?.();
  }

  store.on('event', (ev) => {
    if (ev.type === 'msg.post') dirtyChannels.add(ev.data.channel);
    if (!timer) timer = setTimeout(writeAll, delayMs);
  });

  return {
    flush() {
      if (timer) clearTimeout(timer);
      for (const m of store.state.messages) dirtyChannels.add(m.channel);
      writeAll();
    },
  };
}
